import type { NextPage } from 'next';
import Head from 'next/head';
import PageHeader from '../../components/PageHeader/PageHeader';
import Footer from '../../components/Footer/Footer';
import CountUp from 'react-countup';
import VisibilitySensor from 'react-visibility-sensor';
import styles from '../../styles/Pages.module.css';
const Index: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Dragon Capsule</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>
				<PageHeader />
				<section className={styles.Section__Wrapper}>
					<div
						className={`${styles.background} ${styles.dragon_background}`}></div>
					<div className={styles.text}>
						<h1>Dragon</h1>
						<p>sending humans and cargo into space</p>
					</div>
				</section>
				<section className={styles.Stats}>
					<div className={styles.Stats__Container}>
						<VisibilitySensor
							partialVisibility
							offset={{ bottom: 100 }}>
							{({ isVisible }) => (
								<div className={styles.Stat__Number}>
									{isVisible ? (
										<CountUp start={0} end={34} />
									) : (
										<span>0</span>
									)}
								</div>
							)}
						</VisibilitySensor>
						<h3>Total Launches</h3>
					</div>
					<div className={styles.Stats__Container}>
						<VisibilitySensor
							partialVisibility
							offset={{ bottom: 100 }}>
							{({ isVisible }) => (
								<div className={styles.Stat__Number}>
									{isVisible ? (
										<CountUp start={0} end={31} />
									) : (
										<span>0</span>
									)}
								</div>
							)}
						</VisibilitySensor>
						<h3>Visits to the ISS</h3>
					</div>
					<div className={styles.Stats__Container}>
						<VisibilitySensor
							partialVisibility
							offset={{ bottom: 100 }}>
							{({ isVisible }) => (
								<div className={styles.Stat__Number}>
									{isVisible ? (
										<CountUp start={0} end={13} />
									) : (
										<span>0</span>
									)}
								</div>
							)}
						</VisibilitySensor>
						<h3>Total Reflights</h3>
					</div>
				</section>
				<Footer />
			</main>
		</div>
	);
};

export default Index;
