import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

import Section from '../components/Section/Section';
import PageHeader from '../components/PageHeader/PageHeader';
import Footer from '../components/Footer/Footer';
const Home: NextPage = () => {
	return (
		<div className={styles.Page__Wrapper}>
			<Head>
				<title>SpaceX</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>
				<PageHeader />
				{/* Section A */}
				<Section
					textOne='upcoming launch'
					textTwo='crs-25 mission'
					background='section-a'
					lastSlide={false}
				/>
				{/* Section B */}
				<Section
					textOne='recent launch'
					textTwo='starlink mission'
					background='section-b'
					lastSlide={false}
				/>
				{/* Section C */}
				<Section
					textOne='recent mission'
					textTwo='ses-22 mission'
					background='section-c'
					lastSlide={false}
				/>
				{/* Section D */}
				<Section
					textOne='recent launch'
					textTwo='globalstar fm15 mission'
					background='section-d'
					lastSlide={false}
				/>
				{/* Section E */}
				<Section
					textOne=''
					textTwo='starship update'
					background='section-e'
					lastSlide={false}
				/>
				{/* Section F */}
				<Section
					textOne=''
					textTwo='starship to add nasa astronauts on the moon'
					background='section-f'
					lastSlide={true}
				/>
			</main>
			<Footer />
		</div>
	);
};

export default Home;
